# Generated by Django 6.1.1 on 2026-09-16 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('faculty', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('degree_awarded', models.CharField(max_length=50)),
                ('duration_years', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.department')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('level', models.PositiveSmallIntegerField()),
                ('credits', models.PositiveSmallIntegerField()),
                ('schedule', models.CharField(blank=True, max_length=100)),
                ('prerequisites', models.ManyToManyField(blank=True, to='records.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.department')),
                ('lecturers', models.ManyToManyField(blank=True, related_name='courses', to='records.lecturer')),
                ('programmes', models.ManyToManyField(blank=True, related_name='courses', to='records.programme')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time')], max_length=10)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('year_of_study', models.PositiveSmallIntegerField()),
                ('graduation_status', models.CharField(choices=[('enrolled', 'Enrolled'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn')], default='enrolled', max_length=10)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.lecturer')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.programme')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('funding_source', models.CharField(blank=True, max_length=100)),
                ('lead_lecturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.lecturer')),
                ('students', models.ManyToManyField(blank=True, related_name='research_projects', to='records.student')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateField()),
                ('description', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_records', to='records.student')),
            ],
        ),
        migrations.CreateModel(
            name='LecturerQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=150)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.lecturer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('lecturer', 'qualification'), name='unique_lecturer_qualification')],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'course'), name='unique_enrollment')],
            },
        ),
    ]
