# Generated by Django 6.1.1 on 2026-09-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(('grade__gte', 0), ('grade__lte', 100)), name='grade_range'),
        ),
    ]
