# Generated by Django 6.1.1 on 2026-09-19 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_enrollment_grade_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='funding_source',
        ),
        migrations.AddField(
            model_name='staff',
            name='emergency_contact_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='emergency_contact_phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='committees',
            field=models.ManyToManyField(blank=True, related_name='lecturers', to='records.committee'),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('published_date', models.DateField()),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.lecturer')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='records.researchproject')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('head_lecturer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='records.lecturer')),
            ],
        ),
        migrations.AddField(
            model_name='researchproject',
            name='research_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='records.researchgroup'),
        ),
        migrations.AddField(
            model_name='student',
            name='societies',
            field=models.ManyToManyField(blank=True, related_name='students', to='records.society'),
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=150)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.course')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('course', 'material'), name='unique_course_material')],
            },
        ),
        migrations.CreateModel(
            name='DepartmentResearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_area', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.department')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('department', 'research_area'), name='unique_department_research_area')],
            },
        ),
        migrations.CreateModel(
            name='LecturerExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise', models.CharField(max_length=100)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.lecturer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('lecturer', 'expertise'), name='unique_lecturer_expertise')],
            },
        ),
        migrations.CreateModel(
            name='LecturerResearchInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_interest', models.CharField(max_length=100)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.lecturer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('lecturer', 'research_interest'), name='unique_lecturer_research_interest')],
            },
        ),
        migrations.CreateModel(
            name='ProjectFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_source', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.researchproject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'funding_source'), name='unique_project_funding_source')],
            },
        ),
        migrations.CreateModel(
            name='ProjectOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.researchproject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'outcome'), name='unique_project_outcome')],
            },
        ),
    ]
