# Generated by Django 6.1.1 on 2026-09-19 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_committee_society_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchproject',
            name='research_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='records.researchgroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
