# Generated by Django 6.1.1 on 2026-09-19 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_researchproject_research_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.course'),
        ),
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_links', to='records.course')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='required_by_links', to='records.course')),
            ],
        ),
        migrations.CreateModel(
            name='LecturerCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.course')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.programme')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, through='records.CoursePrerequisite', through_fields=('course', 'prerequisite'), to='records.course'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='lecturers',
        ),
        migrations.AddField(
            model_name='course',
            name='lecturers',
            field=models.ManyToManyField(blank=True, related_name='courses', through='records.LecturerCourse', to='records.lecturer'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='programmes',
        ),
        migrations.AddField(
            model_name='course',
            name='programmes',
            field=models.ManyToManyField(blank=True, related_name='courses', through='records.ProgrammeCourse', to='records.programme'),
        ),
        migrations.AddConstraint(
            model_name='courseprerequisite',
            constraint=models.UniqueConstraint(fields=('course', 'prerequisite'), name='unique_course_prerequisite'),
        ),
        migrations.AddConstraint(
            model_name='lecturercourse',
            constraint=models.UniqueConstraint(fields=('lecturer', 'course'), name='unique_lecturer_course'),
        ),
        migrations.AddConstraint(
            model_name='programmecourse',
            constraint=models.UniqueConstraint(fields=('programme', 'course'), name='unique_programme_course'),
        ),
    ]
